
runtime: nodejs18

env_variables:
  NEXT_PUBLIC_API_URL: "https://api.example.com"  # Your environment variables

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
  - url: /_next/static
    static_dir: .next/static
    secure: always

  - url: /.*
    script: auto
    secure: always
